import { type Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { useSidebar } from '@/hooks/use-sidebar';
import '@/app/styles/globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    const { isOpen, toggle } = useSidebar();

    return (
        <html lang="en" translate="no">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}>
                <div className="flex min-h-screen bg-background text-foreground">
                    <div className="flex flex-1 flex-col">
                        <main className="flex flex-1 flex-col">{children}</main>
                    </div>
                </div>
            </body>
        </html>
    );
}
