import { type Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { AppThemeProvider } from '@/components/layout/app-theme-provider';
import { AppHeader } from '@/components/layout/app-header';
import { AppSidebar } from '@/components/layout/app-sidebar';
import '@/app/styles/globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" translate="no">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}>
                <AppThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <div className="flex min-h-screen bg-background text-foreground">
                        <AppSidebar />
                        <div className="flex flex-1 flex-col">
                            <AppHeader />
                            <main className="flex flex-1 flex-col">{children}</main>
                        </div>
                    </div>
                </AppThemeProvider>
            </body>
        </html>
    );
}
